version: "3.5"
services:
  mc:
    image: mirth450:latest
    container_name: mirth450
    hostname: mirth450
    restart: always
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://mcdb:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - VMOPTIONS=-Xmx512m
    volumes:
      - "./mirth/appdata:/opt/connect/appdata"
      - "./mirth/custom-extensions:/opt/connect/custom-extensions"
      - "./mirth/hl7:/opt/hl7"
      - "./mirth/logs:/opt/connect/logs"
    ports:
      - 8081:8080/tcp
      - 8444:8443/tcp
      - "6600-6699:6600-6699"
    depends_on:
      - mcdb

#**** Database PostGresQL Mirth Connect ****
  mcdb:
    image: postgres:16
    container_name: mcdb
    hostname: mcdb
    restart: always
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
      - POSTGRES_HOST_AUTH_METHOD=trust
#internal exposed port is always 5432 don't change anyway
    expose:
      - 5432
#port 5435 for external tool like dbeavers access
    ports:
      - 5435:5432/tcp
    volumes:
      - "./mirth/pgdata_mirth:/var/lib/postgresql/data"